Add crubot service
RX14/kurisu.rx14.co.uk pull request #1
Opened 2017-09-05 02:06 UTC by azah

2017-09-05 17:57 UTC, RX14 requested changes

2017-09-05 17:57 UTC, RX14 commented on services/http/Caddyfile
> +  proxy / http://localhost:3344/webhook/
no the hostname is `crubot` because all the containers have different IPs

2018-02-16 22:01 UTC, RX14 commented
Well I forgot about this, doubt you still want this to happen.

2018-02-16 22:09 UTC, azah commented
I mean I can just host it myself on my VPS. 

Not sure what the current status of the crystal bot is. Is it still dead?

2018-02-16 22:24 UTC, closed without merging